// <auto-generated />
namespace DAL.FreelanceMusicStore1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview2-19525-03")]
    public sealed partial class AddCollectionOfMiscianstoMusicInstruments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCollectionOfMiscianstoMusicInstruments));
        
        string IMigrationMetadata.Id
        {
            get { return "201911291051089_Add Collection Of Miscians to Music Instruments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
